### PR TITLE
backup-test: Add autodiscovery and `rdedup`

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Comment by dpc** [comment]
Hi. I am a [rdedup](https://github.com/dpc/rdedup) developer and I actually wanted to compare rdedup with other tools myself. Your scripts are exactly what I was looking for, so I just added `rdedup` support.

I have also changed the semantic to automatically discover the paths, unless given manually. This way I don't have to install all of them to compare what I am actually interested in.

Also, I've changed some other details.

Sorry for not making multiple smaller patches myself, but I only had time to get done what I am personally interested in. I hope you'll find it useful.

**Comment by gilbertchen** [comment]
This looks great!  Contributions from other people is exactly what I hoped for when starting this project.  And it is even better when it comes from developers like you!

**Comment by gilbertchen** [comment]
I got the same error when installing rdedup on macOS and Ubuntu:

```
error: failed to run custom build command for `libsodium-sys v0.0.14`
process didn't exit successfully: `/tmp/cargo-install.IjKMaEeJFBcy/release/build/libsodium-sys-20e48ba306557785/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libsodium was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libsodium.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libsodium\' found\n"', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Do you have any experiment results to share?

**Comment by dpc** [comment]
@gilbertchen Something is missing in `PKG_CONFIG_PATH`. As long as `pkg-config --cflags libsodium` doesn't return anything, there's something wrong. Try locating the corresponding `pc` file with something like: `find / | grep libsodium.pc`, and then add it's parent dir to `PKG_CONFIG_PATH`. Make sure `libsodium` is installed, first of all.  :)

According to my own tests `rdedup` is quite competitive speed-wise, but could improve in space savings (ended up with 1.4G, see https://github.com/dpc/rdedup/issues/47 for more). Now that I actually have a benchmark and goal, I'll be able to improve it. Eg. https://github.com/aidanhs/rsroll/pull/5

**Pull request merged**
